### ISSUE TITLE
No events logged to Google Analytics

### ISSUE THREAD

**Issue by chrismllr** [neiker/analytics-react-native#155]
Hey there,

Having issues getting my events logging to GA.

I have been trying to follow this thread https://community.segment.com/t/186txf, and have added a `Mobile` property within GA.

Mapping within Segment destinations:
<img width="658" alt="screen shot 2018-03-06 at 6 30 57 pm" src="https://user-images.githubusercontent.com/9942917/37066827-bbcb4a48-216c-11e8-8e87-e48c995e4910.png">

Is there anything I need to add to my event payloads in order for them to register in GA? Or should I use a `Website` property?

Any help would be greatly appreciated!! 🙏

**Comment by angineering** [comment]
When I set it up I discovered that you need to pass the app name as a property to screen tracking to make google analytics tracking work - example https://medium.com/proximistyle/how-to-add-segment-analytics-to-your-react-native-ios-app-62174ebf6409
