### ISSUE TITLE
Avoid submitting any data till user accept T&C

### ISSUE THREAD

**Issue by obsidianart** [neiker/analytics-react-native#159]
I'm having the issue that I don't want to send any data to the server till the user accept the T&C ("new" European regulation).
I'd love to add a flag called "ingoreFlushRequests" or "doNotSendEvent" (I would love something which clarifies you can revert) and a method to start emitting, like "restoreFlushFuncitonality".
If you like the idea I'll open a PR.
Let me know,
Stefano

**Comment by neiker** [comment]
Hi @obsidianart !

Maybe an `enabled` flag. It's ok for me, go ahead!

**Comment by obsidianart** [comment]
Thank you neiker, unfortunately it's too late for me to work on this, I will close this.
