### ISSUE TITLE
Asserts should only run in dev mode

### ISSUE THREAD

**Issue by angineering** [neiker/analytics-react-native#165]
Asserts from missing userId/anonymousId should not crash a production app.

We have seen a few cases where userId/anonymousId has not been populated correctly for the odd user, and crashes their app every time. The message should be swallowed, and not cause a crash. Analytics is not core to the app execution and therefore should never cause a crash.

My suggestion would be to make all the asserts warnings, except the write key one. If the values are missing, just don't log.

**Comment by angineering** [comment]
If you look at analytics-node they only assert that your write key is present

**Comment by neiker** [comment]
Work in progress here: https://github.com/neiker/analytics-react-native/pull/167

**Comment by neiker** [comment]
Will be included on next release:
https://github.com/neiker/analytics-react-native/releases/tag/v1.3.0-beta.1
