### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by GeoffreyPlitt** [neiker/analytics-react-native#28]
I see you have install instructions, and I know how to call fetch(), but why use this library if I'm just going to make calls to fetch()?

Are you missing instructions on how to import and call track() etc from React-Native land?

**Comment by neiker** [comment]
Using this lib differs from using fetch since it adds abstraction over segment API and requests batching. Please check node lib docs: https://segment.com/docs/sources/server/node/

But you are right, I'll add instructions.
