### ISSUE TITLE
Rename project to analytics-universal

### ISSUE THREAD

**Issue by neiker** [neiker/analytics-react-native#34]
This package works as well in browsers, react native and server side. Make sense the name change. 
- [x] Change react-native references in README and package.json
- [x] Change react-native babel preset
- [x] Remove assert package
- [x] Update badges
- [ ] Add [browsers badge](https://ci.testling.com/guide/quick_start)
- [ ] Rename repo
- [ ] Publish new version

**Comment by ngduc** [comment]
Hi there, any update to this? Thanks.

**Comment by zgeoff** [comment]
@neiker Any particular reason you decided to close this? Does the current project work universally, or is it not headed in that direction now?

**Comment by neiker** [comment]
@meatwallace I'll create another repo called `analytics-universal` and this one will make use of it. And yes, this one currently work universally and will be like this at least until version 2 when all shared code will be moved to `analytics-universal` and here only will be add RN features.
